### ISSUE TITLE
Volttron hangs after starting

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/volttron-core#37]
I followed the [README](https://github.com/VOLTTRON/volttron-core/blob/develop/README.md) to setup the environment using poetry. After running volttron for the first time, the service hangs on the command line and shows this message:

```

Traceback (most recent call last):
  File "/home/bono/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bono/.pyenv/versions/3.9.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1029, in <module>
    _main()
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1023, in _main
    sys.exit(main())
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1017, in main
    start_volttron_process(opts)
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 286, in start_volttron_process
    opts.aip.setup()
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/aip.py", line 427, in setup
    with open(os.path.join(self.install_dir, vip_id, "UUID"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bono/.volttron/agents/7686fcab-e328-4055-8283-13dd709a014b/UUID'
```

Environment:

Ubuntu 2004
Python 3.9.10 (using pyenv to manage different python versions)
Poetry 1.1.13

Steps to reproduce:
1. Clone volttron-core
2. poetry shell
3. poetry install
4. python3 -m volttron.server -vv -l volttron.log&

**Comment by craig8** [comment]
did you clone develop or main?

**Comment by craig8** [comment]
try using the latest wheel from the release tag...

**Comment by bonicim** [comment]
> did you clone develop or main?

I've used both and received the same response.

**Comment by bonicim** [comment]
> try using the latest wheel from the release tag...

I installed the wheel using:

```
pip install https://github.com/VOLTTRON/volttron-core/releases/download/v10.0.1-alpha.5/volttron-10.0.1a5-py3-none-any.whl
```

Then I ran `python3 -m volttron.server -vv -l volttron.log &` and still received the same error:

```
Traceback (most recent call last):
  File "/home/bono/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bono/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1029, in <module>
    _main()
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1023, in _main
    sys.exit(main())
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 1017, in main
    start_volttron_process(opts)
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/__main__.py", line 286, in start_volttron_process
    opts.aip.setup()
  File "/home/bono/Workplace/volttron-project/volttron-core/volttron/server/aip.py", line 427, in setup
    with open(os.path.join(self.install_dir, vip_id, "UUID"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bono/.volttron/agents/7686fcab-e328-4055-8283-13dd709a014b/UUID'
```

**Comment by bonicim** [comment]
The error messages suggest that `volttron.server` is not creating the Volttron Home and all the required subdirectories.

**Comment by craig8** [comment]
Was your volttron_home from a previous version of volttron.  If so you would see this.

**Comment by bonicim** [comment]
I tried setting VOLTTRON_HOME to a different folder. The volttron platform did start running, however, when running 'vctl status', the command just hung. 

I did try something else that worked. I unset the VOLTTRON_HOME and deleted .volttron and .volttron_instances in the $HOME directory. Then I reran the server and `vctl status` and Volttron worked as expected. Regardless, my environment had a previous version of volttron and it needs to be removed before I start testing and developing volttron-core on the same host machine. Issue resolved. No bug found.

**Comment by schandrika** [comment]
When testing this issue. I ran into a dateutil issue. I had to do poetry add python-dateutil. Without that couldn't do a poetry install. Did you run into this?

**Comment by bonicim** [comment]
I did not run into a dateutil issue. I did not do `poetry add python-dateutil`. I was using a fresh install of Ubuntu 20.04 and installed poetry using the recommended script from poetry. I did not do any additional configuration of poetry.
